name: Build and Push to Google Artifact Registry

on:
  push:
    branches: [ "main" , "dev"]

env:
  PROJECT_ID: devsecopsexamproject
  GAR_LOCATION: europe-north1
  GAR_URL: europe-north1-docker.pkg.dev/devsecopsexamproject/exam-project/ui
  SERVICE: ui

jobs:
  build-and-push:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

          
      - name: "Docker auth"
        run: |-
              gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet
              
      - name: Build and Push Container
        run: |-
          echo "${{ secrets.KEY }}" > secret_1.txt
          echo "${{ secrets.DEBUG }}" > secret_2.txt
          echo "${{ secrets.ALLOWED_HOSTS }}" > secret_3.txt
          echo "${{ secrets.SU_PASS }}" > secret_4.txt
          echo "${{ secrets.SU_USER }}" > secret_5.txt
          echo "${{ secrets.SU_EMAIL }}" > secret_6.txt

          cd ${{ github.workspace }}
          IMAGE_TAG=${{env.GAR_URL}}${{ github.ref == 'refs/heads/dev' && '-dev' || '' }}
          docker build . --secret id=secret_1,src=secret_1.txt \
                         --secret id=secret_2,src=secret_2.txt \
                         --secret id=secret_3,src=secret_3.txt \
                         --secret id=secret_4,src=secret_4.txt \
                         --secret id=secret_5,src=secret_5.txt \
                         --secret id=secret_6,src=secret_6.txt \
                         -t  $IMAGE_TAG:latest
          docker push $IMAGE_TAG
          
